Add chip-tool test suite
MonicaisHer/matter-snap-testing-draft pull request #1
Opened 2023-12-15 16:43 UTC by MonicaisHer

2024-01-03 09:26 UTC, MonicaisHer commented on test/suites/chip-tool/chip-all-clusters-minimal-app
Replace with artifact

2024-01-03 13:45 UTC, MonicaisHer commented
Could you please review it @farshidtz?

2024-01-05 11:12 UTC, farshidtz requested changes
When ran locally, the test run successfully only once. After that, chip tool fails to commission with a timeout error. Need to clearing temporary chip files to prevent that.

The change history needs to be improved before merging. In particular, the commit that copies code from [edgex-snap-testing](https://github.com/canonical/edgex-snap-testing) needs to have original [co-authors](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-the-command-line) and more details on the origin. It is best to fork in such situations instead of copy-pasting the code. I also noticed that the original code did not have a license. 

Please refer to other comments inline.

2024-01-05 11:12 UTC, farshidtz commented on build/action.yml
> +        snapcraft-args: ${{ env.base == 'core22' && '--verbose' || '' }}
Checking the base to toggle verbosity is no longer required; see https://bugs.launchpad.net/snapcraft/+bug/1980515

2024-01-08 11:57 UTC, MonicaisHer commented on test/suites/chip-tool/main_test.go
> +var cmd *exec.Cmd
This variable has been initialized outside of the function, so the cluster app instance will be destroyed after the subtest finishes.

2024-01-08 14:48 UTC, farshidtz commented
> This PR has been migrated to a new [PR](https://github.com/MonicaisHer/matter-snap-testing/pull/5). Please see that all review changes have been applied there.

Please sync the changes on main and IENG-881 branches of your new repo back to this repo (rewrite the history by force pushing). Creating an entirely new repo wasn't needed, as that means we lose this PR and reviews.

2024-01-08 14:52 UTC, farshidtz commented on test/suites/chip-tool/main_test.go
> +var cmd *exec.Cmd
> This variable has been initialized outside of the function, so the cluster app instance will be destroyed after the subtest finishes.

I'm not sure what you mean. The `cmd` variable is **declared globally** and **initialized inside the function**. How is the global declaration of this variable associated with destroying the cluster app instance?

2024-01-08 15:58 UTC, closed without merging

2024-01-08 16:09 UTC, MonicaisHer commented
> > This PR has been migrated to a new [PR](https://github.com/MonicaisHer/matter-snap-testing/pull/5). Please see that all review changes have been applied there.
> 
> Please sync the changes on main and IENG-881 branches of your new repo back to this repo (rewrite the history by force pushing). Creating an entirely new repo wasn't needed, as that means we lose this PR and reviews.

The changes have been synced to the main branch, and the commit history has been rewritten on IENG-881 by force pushing. However, after force-pushing, this PR has been automatically closed and can't be reopened. 

Would you like me to open a new PR on this repository and reference this closed PR to maintain a trace of reviews?

2024-01-08 16:36 UTC, farshidtz commented
> The changes have been synced to the main branch, and the commit history has been rewritten on IENG-881 by force pushing. However, after force-pushing, this PR has been automatically closed and can't be reopened.
> 

Something isn't right. 

The history from [IENG-881 branch](https://github.com/canonical/matter-snap-testing/tree/IENG-881) on the new repo:
```
$ git remote -v
origin	https://github.com/canonical/matter-snap-testing.git (fetch)
origin	https://github.com/canonical/matter-snap-testing.git (push)
$ git log --oneline
c747970 (HEAD -> IENG-881, origin/IENG-881) Update Git LFS attribute
5c7869c Remove go routine, remove edgex related utils
940edac Add Git LFS tracking for large binary file
62e3996 Add license
0cb0823 Remove edgex related code, add matter test suite
4ec7094 (origin/main, origin/HEAD, main) Improve input descriptions in snap-testing.yml (#222)
```

The history from IENG-881 on this repo:
```
$ git remote -v
origin	https://github.com/MonicaisHer/matter-snap-testing.git (fetch)
origin	https://github.com/MonicaisHer/matter-snap-testing.git (push)
$ git log --oneline
d75aaf9 (HEAD -> IENG-881, origin/IENG-881) Remove edgex test suites, add matter chip-tool test suite
4ec7094 (origin/main, origin/HEAD, main) Improve input descriptions in snap-testing.yml (#222)
a85ee86 Add channel input for Github snap testing workflow (#221)
```

And then there is this PR's diff showing something completely different. Github can't produce a diff:
![image](https://github.com/MonicaisHer/matter-snap-testing/assets/11150423/d1da6b28-27b6-408d-ad80-bc49c89d54a1)


> Would you like me to open a new PR on this repository and reference this closed PR to maintain a trace of reviews?

If you can't resolve the issue, then yes that would be the second-best option.